//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageFlow.Infra {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageTemplatesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageTemplatesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MessageFlow.Infra.MessageTemplatesResources", typeof(MessageTemplatesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belastingdienst/Toeslagen
        ///Kantoor Utrecht
        ///Postbus 1234, 4590AA UTRECHT
        ///	
        ///{{ aanvrager.naam.voorletters }} {{ aanvrager.naam.achternaam }}
        ///{{ aanvrager.adres.straatnaam }} {{ aanvrager.adres.huisnummer }}
        ///{{ aanvrager.adres.postcode }} {{ aanvrager.adres.woonplaats }}
        ///
        ///Datum: {{ datum_dagtekening }}
        ///
        ///Uw BSN: {{ aanvrager.bsn }}
        ///Kenmerk: TL041
        ///
        ///
        ///### HERINNERING
        ///{% if kgb_variant == true -%}
        ///Onderwerp: We denken dat u kindgebonden budget kunt krijgen
        ///{%- else -%}
        ///Onderwerp: We hebben uw inkom [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Herinneringsbrief_Inkomen {
            get {
                return ResourceManager.GetString("Herinneringsbrief_Inkomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belastingdienst/Toeslagen
        ///Kantoor Utrecht
        ///Postbus 1234, 4590AA UTRECHT
        ///	
        ///{{ aanvrager.naam.voorletters }} {{ aanvrager.naam.achternaam }}
        ///{{ aanvrager.adres.straatnaam }} {{ aanvrager.adres.huisnummer }}
        ///{{ aanvrager.adres.postcode }} {{ aanvrager.adres.woonplaats }}
        ///
        ///Datum: {{ datum_dagtekening }}
        ///
        ///Uw BSN: {{ aanvrager.bsn }}
        ///Kenmerk: TL031
        ///
        ///
        ///{% if kgb_variant -%}
        ///Onderwerp: We denken dat u kindgebonden budget kunt krijgen
        ///{%- else -%}
        ///Onderwerp: We hebben uw inkomen nodig voor uw toeslag        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Vraagbrief_Inkomen {
            get {
                return ResourceManager.GetString("Vraagbrief_Inkomen", resourceCulture);
            }
        }
    }
}
