//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageFlow.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestMessageTemplatesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestMessageTemplatesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MessageFlow.UnitTests.TestMessageTemplatesResources", typeof(TestMessageTemplatesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belastingdienst/Toeslagen
        ///Kantoor Utrecht
        ///Postbus 1234, 4590AA UTRECHT
        ///	
        ///H. de Vries  
        ///Kerkstraat 1  
        ///1234AB AMSTERDAM  
        ///
        ///Datum: 19 november 2023  
        ///
        ///Uw BSN: 123456782  
        ///Kenmerk: TL153
        ///
        ///
        ///### Beschikking
        ///Onderwerp: U krijgt kindgebonden budget
        ///
        ///Beste H. de Vries,
        ///
        ///### Waarom krijgt u deze brief?
        ///Op basis van de van u ontvangen gegevens op 10 november 2023 en 24 november 2023 is besloten uw aanvraag goed te keuren.
        ///
        ///### Besluit
        ///U ontvangt over 2022 kindgebonden budget.
        ///
        ///	
        ///Met vriendel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string expected_beschikking {
            get {
                return ResourceManager.GetString("expected_beschikking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belastingdienst/Toeslagen  
        ///Kantoor Utrecht  
        ///Postbus 1234, 4590AA UTRECHT  
        ///
        ///H. de Vries  
        ///Kerkstraat 1  
        ///1234AB AMSTERDAM  
        ///
        ///Datum: 24 oktober 2023  
        ///
        ///Uw BSN: 123456782  
        ///Kenmerk: TL041  
        ///
        ///
        ///### HERINNERING
        ///Onderwerp: We denken dat u kindgebonden budget kunt krijgen
        ///
        ///Beste H. de Vries,
        ///
        ///### Waarom krijgt u deze brief?
        ///We hebben u om uw inkomen gevraagd in onze brief van 10 oktober 2023. We hebben nog geen reactie van u ontvangen. Misschien bent u het vergeten? 
        ///
        ///### Waarom hebben we u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string expected_rappelbrief {
            get {
                return ResourceManager.GetString("expected_rappelbrief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belastingdienst/Toeslagen  
        ///Kantoor Utrecht  
        ///Postbus 1234, 4590AA UTRECHT  
        ///
        ///H. de Vries  
        ///Kerkstraat 1  
        ///1234AB AMSTERDAM  
        ///
        ///Datum: 12 april 2023  
        ///
        ///Uw BSN: 123456782  
        ///Kenmerk: TL031  
        ///
        ///
        ///Onderwerp: We hebben uw inkomen nodig voor uw toeslag
        ///
        ///Beste H. de Vries,
        ///
        ///### Waarom krijgt u deze brief?
        ///U hebt toeslag over 2022 aangevraagd. We willen uw toeslag graag berekenen. Daarvoor hebben we alleen nog een schatting van uw inkomen over 2022 nodig. Wilt u dit aan ons doorgeven met Mijn toesla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string expected_vraagbrief {
            get {
                return ResourceManager.GetString("expected_vraagbrief", resourceCulture);
            }
        }
    }
}
